# Generated by Django 6.0.4 on 2026-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_notes_user_alter_notes_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
